"""add export_history table, dashboard full_width, notifications required_permission, users can_login, drop sso uq

Revision ID: 24f947e13edc
Revises: t3u4v5w6x7y8
Create Date: 2026-03-26 19:44:49.743637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f947e13edc'
down_revision: Union[str, None] = 't3u4v5w6x7y8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('export_id', sa.String(length=100), nullable=False),
    sa.Column('export_label', sa.String(length=255), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('params_display', sa.Text(), nullable=True),
    sa.Column('oc_id', sa.Integer(), nullable=True),
    sa.Column('oc_name', sa.String(length=255), nullable=True),
    sa.Column('storage_document_id', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['storage_document_id'], ['storage_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_export_history_export_id', 'export_history', ['export_id'], unique=False)
    op.create_index('ix_export_history_feature_name', 'export_history', ['feature_name'], unique=False)
    op.create_index('ix_export_history_user_created', 'export_history', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_export_history_user_id'), 'export_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_export_history_uuid'), 'export_history', ['uuid'], unique=True)
    op.add_column('dashboard_layouts', sa.Column('full_width', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('notifications', sa.Column('required_permission', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_notifications_required_permission'), 'notifications', ['required_permission'], unique=False)
    op.drop_constraint('uq_sso_user_provider', 'sso_accounts', type_='unique')
    op.add_column('users', sa.Column('can_login', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_login')
    op.create_unique_constraint('uq_sso_user_provider', 'sso_accounts', ['user_id', 'provider'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_notifications_required_permission'), table_name='notifications')
    op.drop_column('notifications', 'required_permission')
    op.drop_column('dashboard_layouts', 'full_width')
    op.drop_index(op.f('ix_export_history_uuid'), table_name='export_history')
    op.drop_index(op.f('ix_export_history_user_id'), table_name='export_history')
    op.drop_index('ix_export_history_user_created', table_name='export_history')
    op.drop_index('ix_export_history_feature_name', table_name='export_history')
    op.drop_index('ix_export_history_export_id', table_name='export_history')
    op.drop_table('export_history')
    # ### end Alembic commands ###
