"""add_tts_tables

Revision ID: fc8cad863ba2
Revises: 28efff610c1d
Create Date: 2026-03-27 11:06:06.608064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8cad863ba2'
down_revision: Union[str, None] = '28efff610c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tts_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tts_conversations_user_id'), 'tts_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_tts_conversations_uuid'), 'tts_conversations', ['uuid'], unique=True)
    op.create_table('tts_voices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('voice_type', sa.String(length=20), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('piper_model_name', sa.String(length=255), nullable=True),
    sa.Column('reference_audio_path', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tts_voices_slug'), 'tts_voices', ['slug'], unique=True)
    op.create_index('ix_tts_voices_type_active', 'tts_voices', ['voice_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_tts_voices_user_id'), 'tts_voices', ['user_id'], unique=False)
    op.create_index(op.f('ix_tts_voices_uuid'), 'tts_voices', ['uuid'], unique=True)
    op.create_table('tts_audio_generations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_segment', sa.Integer(), nullable=False),
    sa.Column('total_segments', sa.Integer(), nullable=False),
    sa.Column('output_path', sa.String(length=500), nullable=True),
    sa.Column('output_format', sa.String(length=10), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['tts_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tts_audio_generations_conversation_id'), 'tts_audio_generations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tts_audio_generations_user_id'), 'tts_audio_generations', ['user_id'], unique=False)
    op.create_index(op.f('ix_tts_audio_generations_uuid'), 'tts_audio_generations', ['uuid'], unique=True)
    op.create_index('ix_tts_generations_status', 'tts_audio_generations', ['status'], unique=False)
    op.create_index('ix_tts_generations_user_created', 'tts_audio_generations', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tts_generations_user_created', table_name='tts_audio_generations')
    op.drop_index('ix_tts_generations_status', table_name='tts_audio_generations')
    op.drop_index(op.f('ix_tts_audio_generations_uuid'), table_name='tts_audio_generations')
    op.drop_index(op.f('ix_tts_audio_generations_user_id'), table_name='tts_audio_generations')
    op.drop_index(op.f('ix_tts_audio_generations_conversation_id'), table_name='tts_audio_generations')
    op.drop_table('tts_audio_generations')
    op.drop_index(op.f('ix_tts_voices_uuid'), table_name='tts_voices')
    op.drop_index(op.f('ix_tts_voices_user_id'), table_name='tts_voices')
    op.drop_index('ix_tts_voices_type_active', table_name='tts_voices')
    op.drop_index(op.f('ix_tts_voices_slug'), table_name='tts_voices')
    op.drop_table('tts_voices')
    op.drop_index(op.f('ix_tts_conversations_uuid'), table_name='tts_conversations')
    op.drop_index(op.f('ix_tts_conversations_user_id'), table_name='tts_conversations')
    op.drop_table('tts_conversations')
    # ### end Alembic commands ###
