services:
  api:
    volumes:
      - ./api/src:/app/src
      - ./api/alembic:/app/alembic
      - ./api/tests:/app/tests
      - ./api/pytest.ini:/app/pytest.ini
      - ./api/requirements-test.txt:/app/requirements-test.txt
      - ./backups:/app/backups
      - ./uploads:/app/uploads

  worker:
    volumes:
      - ./api/src:/app/src
      - ./uploads:/app/uploads

  tts-worker:
    volumes:
      - ./api/src:/app/src
      - ./uploads:/app/uploads

  app:
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
      - ./app/index.html:/app/index.html
      - ./app/vite.config.ts:/app/vite.config.ts
      - ./app/package.json:/app/package.json
